modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="h1v3"
version="1.0.0"
displayName="H1V3"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="aterrell, MCreator"

[[dependencies.h1v3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




